//
//  SoapMessage.m
//  MatteiPhotoExport
//
//  Created by Matt on 11/5/10.
//  Copyright 2010 . All rights reserved.
//

#import "SoapMessage.h"

#import "Constants.h"

@implementation SoapMessage

@synthesize action, message, password, username;

- (void) dealloc {
	self.action = nil;
	self.message = nil;
	self.password = nil;
	self.username = nil;
	[super dealloc];
}

- (NSXMLDocument *) asXml {
	NSXMLNode *nsSoap = [NSXMLNode namespaceWithName:@"soap-env" stringValue:@"http://schemas.xmlsoap.org/soap/envelope/"];
    NSXMLElement *envelope = [NSXMLElement elementWithName:@"soap-env:Envelope" URI:[nsSoap stringValue]];
	[envelope addNamespace:nsSoap];
	NSXMLDocument *xmlDoc = [NSXMLDocument document];
	[xmlDoc setVersion:@"1.0"];
	[xmlDoc setCharacterEncoding:@"UTF-8"];
	[xmlDoc addChild:[NSXMLNode commentWithStringValue:[NSString stringWithFormat:
														@" Generated by Matte iPhoto Export Plugin %@ ", 
														MatteExportPluginVersion]]];
	[xmlDoc addChild:envelope];

	// header
	NSXMLElement *header = [NSXMLElement elementWithName:@"soap-env:Header" URI:[nsSoap stringValue]];
	[envelope addChild:header];
	
	// wsse
	if ( self.username != nil ) {
		NSXMLNode *nsWsse = [NSXMLNode namespaceWithName:@"wsse" 
											 stringValue:@"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"];
		NSXMLElement *security = [NSXMLElement elementWithName:@"wsse:Security" URI:[nsWsse stringValue]];
		[security addNamespace:nsWsse];
		[header addChild:security];
		NSXMLElement *token = [NSXMLElement elementWithName:@"wsse:UsernameToken" URI:[nsWsse stringValue]];
		[security addChild:token];
		
		NSXMLElement *user = [NSXMLElement elementWithName:@"wsse:Username" URI:[nsWsse stringValue]];
		[user setStringValue:username];
		[token addChild:user];
		
		NSXMLElement *pass = [NSXMLElement elementWithName:@"wsse:Password" URI:[nsWsse stringValue]];
		[pass setStringValue:password];
		[token addChild:pass];
	}
	
	// body
	NSXMLElement *body = [NSXMLElement elementWithName:@"soap-env:Body" URI:[nsSoap stringValue]];
	[envelope addChild:body];
	
	// message
	[body addChild:message];
	
	return xmlDoc;
}

@end
