/* soapStub.h
   Generated by gSOAP 2.7.9l from MatteService.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_wsu__tTimestampFault
#define SOAP_TYPE_wsu__tTimestampFault (6)
/* wsu:tTimestampFault */
enum wsu__tTimestampFault {wsu__MessageExpired = 0};
#endif

#ifndef SOAP_TYPE_wsse__FaultcodeEnum
#define SOAP_TYPE_wsse__FaultcodeEnum (8)
/* wsse:FaultcodeEnum */
enum wsse__FaultcodeEnum {wsse__UnsupportedSecurityToken = 0, wsse__UnsupportedAlgorithm = 1, wsse__InvalidSecurity = 2, wsse__InvalidSecurityToken = 3, wsse__FailedAuthentication = 4, wsse__FailedCheck = 5, wsse__SecurityTokenUnavailable = 6};
#endif

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (63)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

#ifndef SOAP_TYPE_m__album_import_sort_type
#define SOAP_TYPE_m__album_import_sort_type (65)
/* m:album-import-sort-type */
enum m__album_import_sort_type {m__album_import_sort_type__date = 0};
#endif

/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE__wsu__Timestamp
#define SOAP_TYPE__wsu__Timestamp (7)
/* wsu:Timestamp */
struct _wsu__Timestamp
{
	char *wsu__Id;	/* optional attribute of type xsd:string */
	char *Created;	/* optional element of type xsd:string */
	char *Expires;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__UsernameToken
#define SOAP_TYPE__wsse__UsernameToken (9)
/* wsse:UsernameToken */
struct _wsse__UsernameToken
{
	char *Username;	/* optional element of type xsd:string */
	struct _wsse__Password *Password;	/* optional element of type wsse:Password */
	char *Nonce;	/* optional element of type xsd:string */
	char *wsu__Created;	/* optional element of type xsd:string */
	char *wsu__Id;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__BinarySecurityToken
#define SOAP_TYPE__wsse__BinarySecurityToken (12)
/* Primitive wsse:BinarySecurityToken schema type: */
struct _wsse__BinarySecurityToken
{
	char *__item;
	char *wsu__Id;	/* optional attribute of type xsd:string */
	char *ValueType;	/* optional attribute of type xsd:string */
	char *EncodingType;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__Reference
#define SOAP_TYPE__wsse__Reference (13)
/* wsse:Reference */
struct _wsse__Reference
{
	char *URI;	/* optional attribute of type xsd:string */
	char *ValueType;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__Embedded
#define SOAP_TYPE__wsse__Embedded (14)
/* wsse:Embedded */
struct _wsse__Embedded
{
	char *wsu__Id;	/* optional attribute of type xsd:string */
	char *ValueType;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__KeyIdentifier
#define SOAP_TYPE__wsse__KeyIdentifier (15)
/* Primitive wsse:KeyIdentifier schema type: */
struct _wsse__KeyIdentifier
{
	char *__item;
	char *wsu__Id;	/* optional attribute of type xsd:string */
	char *ValueType;	/* optional attribute of type xsd:string */
	char *EncodingType;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__SecurityTokenReference
#define SOAP_TYPE__wsse__SecurityTokenReference (16)
/* wsse:SecurityTokenReference */
struct _wsse__SecurityTokenReference
{
	struct _wsse__Reference *Reference;	/* optional element of type wsse:Reference */
	struct _wsse__KeyIdentifier *KeyIdentifier;	/* optional element of type wsse:KeyIdentifier */
	struct _wsse__Embedded *Embedded;	/* optional element of type wsse:Embedded */
	char *wsu__Id;	/* optional attribute of type xsd:string */
	char *Usage;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__SignatureType
#define SOAP_TYPE_ds__SignatureType (20)
/* ds:SignatureType */
struct ds__SignatureType
{
	struct ds__SignedInfoType *SignedInfo;	/* optional element of type ds:SignedInfoType */
	char *SignatureValue;	/* optional element of type xsd:string */
	struct ds__KeyInfoType *KeyInfo;	/* optional element of type ds:KeyInfoType */
	char *Id;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__c14n__InclusiveNamespaces
#define SOAP_TYPE__c14n__InclusiveNamespaces (29)
/* c14n:InclusiveNamespaces */
struct _c14n__InclusiveNamespaces
{
	char *PrefixList;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__TransformType
#define SOAP_TYPE_ds__TransformType (30)
/* ds:TransformType */
struct ds__TransformType
{
	struct _c14n__InclusiveNamespaces *c14n__InclusiveNamespaces;	/* optional element of type c14n:InclusiveNamespaces */
	char *__any;
	char *Algorithm;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__KeyInfoType
#define SOAP_TYPE_ds__KeyInfoType (23)
/* ds:KeyInfoType */
struct ds__KeyInfoType
{
	char *KeyName;	/* optional element of type xsd:string */
	struct ds__KeyValueType *KeyValue;	/* optional element of type ds:KeyValueType */
	struct ds__RetrievalMethodType *RetrievalMethod;	/* optional element of type ds:RetrievalMethodType */
	struct ds__X509DataType *X509Data;	/* optional element of type ds:X509DataType */
	struct _wsse__SecurityTokenReference *wsse__SecurityTokenReference;	/* optional element of type wsse:SecurityTokenReference */
	char *Id;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__SignedInfoType
#define SOAP_TYPE_ds__SignedInfoType (21)
/* ds:SignedInfoType */
struct ds__SignedInfoType
{
	struct ds__CanonicalizationMethodType *CanonicalizationMethod;	/* required element of type ds:CanonicalizationMethodType */
	struct ds__SignatureMethodType *SignatureMethod;	/* required element of type ds:SignatureMethodType */
	int __sizeReference;	/* sequence of elements <Reference> */
	struct ds__ReferenceType **Reference;	/* required element of type ds:ReferenceType */
	char *Id;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__CanonicalizationMethodType
#define SOAP_TYPE_ds__CanonicalizationMethodType (25)
/* ds:CanonicalizationMethodType */
struct ds__CanonicalizationMethodType
{
	char *Algorithm;	/* required attribute of type xsd:string */
	struct _c14n__InclusiveNamespaces *c14n__InclusiveNamespaces;	/* optional element of type c14n:InclusiveNamespaces */
};
#endif

#ifndef SOAP_TYPE_ds__SignatureMethodType
#define SOAP_TYPE_ds__SignatureMethodType (26)
/* ds:SignatureMethodType */
struct ds__SignatureMethodType
{
	int *HMACOutputLength;	/* optional element of type xsd:int */
	char *Algorithm;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__ReferenceType
#define SOAP_TYPE_ds__ReferenceType (27)
/* ds:ReferenceType */
struct ds__ReferenceType
{
	struct ds__TransformsType *Transforms;	/* optional element of type ds:TransformsType */
	struct ds__DigestMethodType *DigestMethod;	/* required element of type ds:DigestMethodType */
	char *DigestValue;	/* required element of type xsd:string */
	char *Id;	/* optional attribute of type xsd:string */
	char *URI;	/* optional attribute of type xsd:string */
	char *Type;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__TransformsType
#define SOAP_TYPE_ds__TransformsType (28)
/* ds:TransformsType */
struct ds__TransformsType
{
	int __sizeTransform;	/* sequence of elements <Transform> */
	struct ds__TransformType *Transform;	/* required element of type ds:TransformType */
};
#endif

#ifndef SOAP_TYPE_ds__DigestMethodType
#define SOAP_TYPE_ds__DigestMethodType (32)
/* ds:DigestMethodType */
struct ds__DigestMethodType
{
	char *Algorithm;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__KeyValueType
#define SOAP_TYPE_ds__KeyValueType (33)
/* ds:KeyValueType */
struct ds__KeyValueType
{
	struct ds__DSAKeyValueType *DSAKeyValue;	/* required element of type ds:DSAKeyValueType */
	struct ds__RSAKeyValueType *RSAKeyValue;	/* required element of type ds:RSAKeyValueType */
};
#endif

#ifndef SOAP_TYPE_ds__RetrievalMethodType
#define SOAP_TYPE_ds__RetrievalMethodType (35)
/* ds:RetrievalMethodType */
struct ds__RetrievalMethodType
{
	struct ds__TransformsType *Transforms;	/* optional element of type ds:TransformsType */
	char *URI;	/* optional attribute of type xsd:string */
	char *Type;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__X509DataType
#define SOAP_TYPE_ds__X509DataType (37)
/* ds:X509DataType */
struct ds__X509DataType
{
	struct ds__X509IssuerSerialType *X509IssuerSerial;	/* required element of type ds:X509IssuerSerialType */
	char *X509SKI;	/* required element of type xsd:string */
	char *X509SubjectName;	/* required element of type xsd:string */
	char *X509Certificate;	/* required element of type xsd:string */
	char *X509CRL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__X509IssuerSerialType
#define SOAP_TYPE_ds__X509IssuerSerialType (40)
/* ds:X509IssuerSerialType */
struct ds__X509IssuerSerialType
{
	char *X509IssuerName;	/* required element of type xsd:string */
	int X509SerialNumber;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ds__DSAKeyValueType
#define SOAP_TYPE_ds__DSAKeyValueType (41)
/* ds:DSAKeyValueType */
struct ds__DSAKeyValueType
{
	char *G;	/* optional element of type xsd:string */
	char *Y;	/* required element of type xsd:string */
	char *J;	/* optional element of type xsd:string */
	char *P;	/* required element of type xsd:string */
	char *Q;	/* required element of type xsd:string */
	char *Seed;	/* required element of type xsd:string */
	char *PgenCounter;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ds__RSAKeyValueType
#define SOAP_TYPE_ds__RSAKeyValueType (42)
/* ds:RSAKeyValueType */
struct ds__RSAKeyValueType
{
	char *Modulus;	/* required element of type xsd:string */
	char *Exponent;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__Security
#define SOAP_TYPE__wsse__Security (54)
/* wsse:Security */
struct _wsse__Security
{
	struct _wsu__Timestamp *wsu__Timestamp;	/* optional element of type wsu:Timestamp */
	struct _wsse__UsernameToken *UsernameToken;	/* optional element of type wsse:UsernameToken */
	struct _wsse__BinarySecurityToken *BinarySecurityToken;	/* optional element of type wsse:BinarySecurityToken */
	struct ds__SignatureType *ds__Signature;	/* optional element of type ds:SignatureType */
	char *SOAP_ENV__actor;	/* optional attribute of type xsd:string */
	char *SOAP_ENV__role;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__wsse__Password
#define SOAP_TYPE__wsse__Password (10)
/* Primitive wsse:Password schema type: */
struct _wsse__Password
{
	char *__item;
	char *Type;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (59)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_m__get_collection_list_request_type
#define SOAP_TYPE_m__get_collection_list_request_type (66)
/* m:get-collection-list-request-type */
struct m__get_collection_list_request_type
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_m__get_collection_list_response_type
#define SOAP_TYPE_m__get_collection_list_response_type (67)
/* m:get-collection-list-response-type */
struct m__get_collection_list_response_type
{
	int __sizecollection;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <collection> */
	struct m__collection_list_item_type *collection;	/* optional element of type m:collection-list-item-type */
};
#endif

#ifndef SOAP_TYPE_m__collection_list_item_type
#define SOAP_TYPE_m__collection_list_item_type (68)
/* m:collection-list-item-type */
struct m__collection_list_item_type
{
	LONG64 collection_id;	/* required attribute of type xsd:long */
	char *name;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_m__add_media_request_type
#define SOAP_TYPE_m__add_media_request_type (71)
/* m:add-media-request-type */
struct m__add_media_request_type
{
	struct m__collection_import_type *collection_import;	/* required element of type m:collection-import-type */
	struct m__media_data_type *media_data;	/* optional element of type m:media-data-type */
	LONG64 collection_id;	/* required attribute of type xsd:long */
	char *local_tz;	/* optional attribute of type xsd:string */
	char *media_tz;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_m__add_media_response_type
#define SOAP_TYPE_m__add_media_response_type (76)
/* m:add-media-response-type */
struct m__add_media_response_type
{
	char *message;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	enum xsd__boolean success;	/* required attribute of type xsd:boolean */
	LONG64 *ticket;	/* optional attribute of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_m__collection_import_type
#define SOAP_TYPE_m__collection_import_type (72)
/* m:collection-import-type */
struct m__collection_import_type
{
	int __sizealbum;	/* sequence of elements <album> */
	struct m__album_import_type *album;	/* optional element of type m:album-import-type */
	int __sizeitem;	/* sequence of elements <item> */
	struct m__item_import_type *item;	/* optional element of type m:item-import-type */
	char *name;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_m__base_import_type
#define SOAP_TYPE_m__base_import_type (82)
/* m:base-import-type */
struct m__base_import_type
{
	char *comment;	/* optional element of type xsd:string */
	char *name;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_m__media_data_type
#define SOAP_TYPE_m__media_data_type (74)
/* Primitive m:media-data-type schema type: */
struct m__media_data_type
{
	struct xsd__base64Binary __item;
	char *xmime5__contentType;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_m__album_import_type
#define SOAP_TYPE_m__album_import_type (78)
/* m:album-import-type */
struct m__album_import_type
{
	char *comment;	/* optional element of type xsd:string */
	char *name;	/* optional attribute of type xsd:string */
	int __sizeitem;	/* sequence of elements <item> */
	struct m__item_import_type *item;	/* optional element of type m:item-import-type */
	int __sizealbum;	/* sequence of elements <album> */
	struct m__album_import_type *album;	/* optional element of type m:album-import-type */
	enum m__album_import_sort_type sort;	/* optional attribute of type m:album-import-sort-type */
	char *album_date;	/* optional attribute of type xsd:date */
	time_t *creation_date;	/* optional attribute of type xsd:dateTime */
	time_t *modify_date;	/* optional attribute of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_m__item_import_type
#define SOAP_TYPE_m__item_import_type (80)
/* m:item-import-type */
struct m__item_import_type
{
	char *comment;	/* optional element of type xsd:string */
	char *name;	/* optional attribute of type xsd:string */
	char *keywords;	/* optional element of type xsd:string */
	int __sizemeta;	/* sequence of elements <meta> */
	struct m__metadata_import_type *meta;	/* optional element of type m:metadata-import-type */
	char *archive_path;	/* required attribute of type xsd:string */
	float *rating;	/* optional attribute of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_m__metadata_import_type
#define SOAP_TYPE_m__metadata_import_type (85)
/* Primitive m:metadata-import-type schema type: */
struct m__metadata_import_type
{
	char *__item;
	char *name;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (89)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	struct _wsse__Security *wsse__Security;	/* mustUnderstand */
};
#endif

#ifndef SOAP_TYPE___mws__GetCollectionList
#define SOAP_TYPE___mws__GetCollectionList (94)
/* Operation wrapper: */
struct __mws__GetCollectionList
{
	struct m__get_collection_list_request_type *m__GetCollectionListRequest;	/* optional element of type m:get-collection-list-request-type */
};
#endif

#ifndef SOAP_TYPE___mws__AddMedia
#define SOAP_TYPE___mws__AddMedia (98)
/* Operation wrapper: */
struct __mws__AddMedia
{
	struct m__add_media_request_type *m__AddMediaRequest;	/* optional element of type m:add-media-request-type */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (99)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (101)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (104)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (105)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (64)
typedef char *xsd__date;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/

typedef enum wsu__tTimestampFault wsu__tTimestampFault;
typedef enum wsse__FaultcodeEnum wsse__FaultcodeEnum;
typedef struct _wsu__Timestamp _wsu__Timestamp;
typedef struct _wsse__UsernameToken _wsse__UsernameToken;
typedef struct _wsse__BinarySecurityToken _wsse__BinarySecurityToken;
typedef struct _wsse__Reference _wsse__Reference;
typedef struct _wsse__Embedded _wsse__Embedded;
typedef struct _wsse__KeyIdentifier _wsse__KeyIdentifier;
typedef struct _wsse__SecurityTokenReference _wsse__SecurityTokenReference;
typedef struct ds__SignatureType ds__SignatureType;
typedef struct _c14n__InclusiveNamespaces _c14n__InclusiveNamespaces;
typedef struct ds__TransformType ds__TransformType;
typedef struct ds__KeyInfoType ds__KeyInfoType;
typedef struct ds__SignedInfoType ds__SignedInfoType;
typedef struct ds__CanonicalizationMethodType ds__CanonicalizationMethodType;
typedef struct ds__SignatureMethodType ds__SignatureMethodType;
typedef struct ds__ReferenceType ds__ReferenceType;
typedef struct ds__TransformsType ds__TransformsType;
typedef struct ds__DigestMethodType ds__DigestMethodType;
typedef struct ds__KeyValueType ds__KeyValueType;
typedef struct ds__RetrievalMethodType ds__RetrievalMethodType;
typedef struct ds__X509DataType ds__X509DataType;
typedef struct ds__X509IssuerSerialType ds__X509IssuerSerialType;
typedef struct ds__DSAKeyValueType ds__DSAKeyValueType;
typedef struct ds__RSAKeyValueType ds__RSAKeyValueType;
typedef struct _wsse__Security _wsse__Security;
typedef struct _wsse__Password _wsse__Password;

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __mws__GetCollectionList(struct soap*, struct m__get_collection_list_request_type *m__GetCollectionListRequest, struct m__get_collection_list_response_type *m__GetCollectionListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __mws__AddMedia(struct soap*, struct m__add_media_request_type *m__AddMediaRequest, struct m__add_media_response_type *m__AddMediaResponse);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___mws__GetCollectionList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct m__get_collection_list_request_type *m__GetCollectionListRequest, struct m__get_collection_list_response_type *m__GetCollectionListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___mws__AddMedia(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct m__add_media_request_type *m__AddMediaRequest, struct m__add_media_response_type *m__AddMediaResponse);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___mws__GetCollectionList(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___mws__AddMedia(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
