/* soapClient.c
   Generated by gSOAP 2.7.9l from MatteService.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.9l 2007-12-15 23:10:26 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___mws__GetCollectionList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct m__get_collection_list_request_type *m__GetCollectionListRequest, struct m__get_collection_list_response_type *m__GetCollectionListResponse)
{	struct __mws__GetCollectionList soap_tmp___mws__GetCollectionList;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/matte/ws/Matte";
	if (!soap_action)
		soap_action = "http://msqr.us/matte/ws/GetCollectionList";
	soap->encodingStyle = NULL;
	soap_tmp___mws__GetCollectionList.m__GetCollectionListRequest = m__GetCollectionListRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___mws__GetCollectionList(soap, &soap_tmp___mws__GetCollectionList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___mws__GetCollectionList(soap, &soap_tmp___mws__GetCollectionList, "-mws:GetCollectionList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___mws__GetCollectionList(soap, &soap_tmp___mws__GetCollectionList, "-mws:GetCollectionList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_m__get_collection_list_response_type(soap, m__GetCollectionListResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_m__get_collection_list_response_type(soap, m__GetCollectionListResponse, "m:GetCollectionListResponse", "m:get-collection-list-response-type");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___mws__AddMedia(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct m__add_media_request_type *m__AddMediaRequest, struct m__add_media_response_type *m__AddMediaResponse)
{	struct __mws__AddMedia soap_tmp___mws__AddMedia;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/matte/ws/Matte";
	if (!soap_action)
		soap_action = "http://msqr.us/matte/ws/AddMedia";
	soap->encodingStyle = NULL;
	soap_tmp___mws__AddMedia.m__AddMediaRequest = m__AddMediaRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___mws__AddMedia(soap, &soap_tmp___mws__AddMedia);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___mws__AddMedia(soap, &soap_tmp___mws__AddMedia, "-mws:AddMedia", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___mws__AddMedia(soap, &soap_tmp___mws__AddMedia, "-mws:AddMedia", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_m__add_media_response_type(soap, m__AddMediaResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_m__add_media_response_type(soap, m__AddMediaResponse, "m:AddMediaResponse", "m:add-media-response-type");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
